# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"
  storybook:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '6006:6006'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn storybook:serve"
